version: '3.7'

services:
  sga-athena:
      environment:
          APP_ENV: 'prod'
          # database connection
          DATABASE_URL: 'mysql://novosga:MySQL_App_P4ssW0rd@mysqldb:3306/novosga2?charset=utf8mb4&serverVersion=5.7'
          # default admin user
          NOVOSGA_ADMIN_USERNAME: 'admin'
          NOVOSGA_ADMIN_PASSWORD: '123456'
          NOVOSGA_ADMIN_FIRSTNAME: 'Administrator'
          NOVOSGA_ADMIN_LASTNAME: 'Global'
          # default unity
          NOVOSGA_UNITY_NAME: 'My Unity'
          NOVOSGA_UNITY_CODE: 'U01'
          # default no-priority
          NOVOSGA_NOPRIORITY_NAME: 'Normal'
          NOVOSGA_NOPRIORITY_DESCRIPTION: 'Normal service'
          # default priority
          NOVOSGA_PRIORITY_NAME: 'Priority'
          NOVOSGA_PRIORITY_DESCRIPTION: 'Priority service'
          # default place
          NOVOSGA_PLACE_NAME: 'Box'
          # Set TimeZone and locale
          TZ: 'America/Sao_Paulo'
          LANGUAGE: 'pt_BR'
      build:
        context: ./
        dockerfile: Dockerfile
      image: sga-athena
      container_name: sga-athena
      restart: unless-stopped
      working_dir: /var/www
      volumes:
        - ./sga:/var/www
      networks:
        - internet


  nginx:
      image: nginx
      container_name: sga-athena
      restart: unless-stopped
      ports:
        - 8000:80
      volume:
        - ./sga:/var/www
        - ./docker-compose/nginx:/etc/nginx/config
      networks:
        - internet

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'novosga'
      MYSQL_DATABASE: 'novosga2'
      MYSQL_ROOT_PASSWORD: 'MySQL_r00t_P4ssW0rd'
      MYSQL_PASSWORD: 'MySQL_App_P4ssW0rd'
      # Set TimeZone
      TZ: 'America/Sao_Paulo'